package kasir_app;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import javax.swing.JTextField;
/**
 *
 * @author Muh Israjab DS
 */
public class pegawai extends javax.swing.JFrame {
     private PreparedStatement stat;
    private ResultSet rs;
    private DefaultTableModel model = null;
    koneksi k = new koneksi();
    private String tglLahir;
 
    public pegawai() {
        Icons();
        initComponents();
        k.connect();
        inputId.setVisible(false);
        refreshTable();
    }
    public class pegawais extends pegawai {
    int id;
    String nama_pegawai, Jenis_kelamin, alamat, no_telp, jabatan, gaji, tanggal_lahir, tanggal_masuk;

    public pegawais() {
        this.id = 0;
        this.nama_pegawai = inputNama.getText();
         this.tanggal_lahir = ((JTextField)inputTglLahir.getDateEditor().getUiComponent()).getText();
        this.Jenis_kelamin = comboJKL.getSelectedItem().toString();
        this.alamat = inputAlamat.getText();
        this.no_telp = inputTelp.getText();
        this.jabatan = inputJabatan.getText();
        this.gaji = inputGaji.getText();
         this.tanggal_masuk = ((JTextField)inpuTglMasuk.getDateEditor().getUiComponent()).getText();
    }
}

    
 public void refreshTable()
       {
            model = new DefaultTableModel();
            model.addColumn("ID PEGAWAI");
            model.addColumn("NAMA PEGAWAI");
            model.addColumn("JENIS KELAMIN");
            model.addColumn("TANGGAL LAHIR");
            model.addColumn("ALAMAT");
            model.addColumn("NO TELP");
            model.addColumn("JABATAN");
            model.addColumn("GAJI");
            model.addColumn("TANGGAL MASUK");
           tblPegawai.setModel(model);
           try {
               stat = k.getCon().prepareStatement("SELECT * FROM tbl_pegawai");
               rs = stat.executeQuery();
               while(rs.next()){
                   Object[] data = {
                       rs.getString("id_pegawai"),
                       rs.getString("nama_pegawai"),
                       rs.getString("jk"),
                       rs.getString("tgl_lahir"),
                       rs.getString("alamat"),
                       rs.getString("telp"),
                       rs.getString("jabatan"),
                       rs.getString("gaji"),
                       rs.getString("tgl_masuk")
                   };
                   model.addRow(data);
               }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
           inputId.setText("");
           inputNama.setText("");
           inputAlamat.setText("");
           inputTelp.setText("");
           inputJabatan.setText("");
           inputGaji.setText("");
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        inputId = new javax.swing.JTextField();
        inputNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputTglLahir = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        inputAlamat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        inputTelp = new javax.swing.JTextField();
        inputJabatan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        inputGaji = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPegawai = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comboJKL = new javax.swing.JComboBox<>();
        inpuTglMasuk = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        bgPegawai = new javax.swing.JLabel();

        jTextField8.setText("jTextField8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1872, 930));
        setPreferredSize(new java.awt.Dimension(1875, 955));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pegawai");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(337, 27, 149, 44);
        getContentPane().add(inputId);
        inputId.setBounds(71, 127, 0, 0);

        inputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaActionPerformed(evt);
            }
        });
        getContentPane().add(inputNama);
        inputNama.setBounds(50, 130, 681, 35);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Pegawai");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 100, 106, 18);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis Kelamin");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 180, 103, 18);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tanggal Lahir");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 260, 99, 18);
        getContentPane().add(inputTglLahir);
        inputTglLahir.setBounds(50, 280, 681, 35);

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 340, 50, 18);
        getContentPane().add(inputAlamat);
        inputAlamat.setBounds(50, 360, 681, 35);

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No Telp");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 420, 56, 18);
        getContentPane().add(inputTelp);
        inputTelp.setBounds(50, 450, 681, 35);
        getContentPane().add(inputJabatan);
        inputJabatan.setBounds(50, 530, 681, 35);

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jabatan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(71, 582, 56, 18);
        getContentPane().add(inputGaji);
        inputGaji.setBounds(50, 610, 681, 35);

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gaji");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 580, 28, 18);

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tanggal Masuk");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 670, 106, 18);

        btnCreate.setBackground(new java.awt.Color(0, 0, 0));
        btnCreate.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("INPUT");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreate);
        btnCreate.setBounds(20, 790, 153, 49);

        btnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdate.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(320, 790, 153, 49);

        btnDelete.setBackground(new java.awt.Color(0, 0, 0));
        btnDelete.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(600, 790, 153, 48);

        tblPegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID PEGAWAI", "NAMA PEGAWAI", "JENIS KELAMIN", "TANGGAL LAHIR", "ALAMAT", "NO TELP", "JABATAN", "GAJI", "TANGGAL MASUK"
            }
        ));
        tblPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPegawaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPegawai);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(770, 140, 1082, 623);

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("TABEL PEGAWAI :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(780, 100, 140, 18);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kasir_app/BackButton .png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 148, 50);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kasir_app/logout.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(1790, 0, 80, 90);

        comboJKL.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        comboJKL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Silahkan Pilih Jenis Kelamin --", "Laki-Laki", "Perempuan" }));
        comboJKL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJKLActionPerformed(evt);
            }
        });
        getContentPane().add(comboJKL);
        comboJKL.setBounds(50, 200, 680, 40);

        inpuTglMasuk.setMinimumSize(new java.awt.Dimension(27, 35));
        getContentPane().add(inpuTglMasuk);
        inpuTglMasuk.setBounds(50, 690, 681, 35);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Muh Israjab DS\\OneDrive\\Desktop\\kasir_app\\src\\kasir_app\\tranpegawai.png")); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 0, 1870, 920);

        bgPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kasir_app/bgPegawai.png"))); // NOI18N
        bgPegawai.setText("jLabel14");
        getContentPane().add(bgPegawai);
        bgPegawai.setBounds(0, -20, 1870, 1260);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        menu_admin m = new menu_admin();
            m.setVisible(true);
            dispose();   
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
       login l = new login();
       l.setVisible(true);
       dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void comboJKLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJKLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboJKLActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        pegawais p = new pegawais();
        try {
            stat = k.getCon().prepareStatement("INSERT INTO tbl_pegawai VALUES (?,?,?,?,?,?,?,?,?)");
            stat.setInt(1,0);
            stat.setString(2, p.nama_pegawai);
            stat.setString(3, p.Jenis_kelamin);
            stat.setString(4, p.tanggal_lahir);
            stat.setString(5, p.alamat);
            stat.setString(6, p.no_telp);
            stat.setString(7, p.jabatan);
            stat.setString(8, p.gaji);
            stat.setString(9, p.tanggal_masuk);
            stat.executeUpdate();
            refreshTable();
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DI INPUT !");
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }                 
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
         try {
            stat = k.getCon().prepareStatement("delete from tbl_pegawai where id_pegawai= ?");
            stat.setString(1,inputId.getText());
            stat.executeUpdate();
            refreshTable();
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DI HAPUS !");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPegawaiMouseClicked
        inputId.setText(model.getValueAt(tblPegawai.getSelectedRow(), 0).toString());
       inputNama.setText(model.getValueAt(tblPegawai.getSelectedRow(), 1).toString());
         comboJKL.setSelectedItem(model.getValueAt(tblPegawai.getSelectedRow(), 2).toString());
         inputTglLahir.setDateFormatString(model.getValueAt(tblPegawai.getSelectedRow(), 3).toString());
          inputAlamat.setText(model.getValueAt(tblPegawai.getSelectedRow(), 4).toString());
           inputTelp.setText(model.getValueAt(tblPegawai.getSelectedRow(), 5).toString());
            inputJabatan.setText(model.getValueAt(tblPegawai.getSelectedRow(), 6).toString());
               inputGaji.setText(model.getValueAt(tblPegawai.getSelectedRow(), 7).toString());
                  inpuTglMasuk.setDateFormatString(model.getValueAt(tblPegawai.getSelectedRow(), 8).toString());
    }//GEN-LAST:event_tblPegawaiMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         pegawais p = new pegawais();
        try {       
             stat = k.getCon().prepareStatement("UPDATE tbl_pegawai SET nama_pegawai=?,"
            + "jk=?,tgl_lahir=?,alamat=?,telp=?,jabatan=?,gaji=?,tgl_masuk=? WHERE id_pegawai=?");
            stat.setString(1, inputNama.getText());
            stat.setString(2, p.Jenis_kelamin);
            stat.setString(3, p.tanggal_lahir);
            stat.setString(4, p.alamat);
            stat.setString(5, p.no_telp);
            stat.setString(6, p.jabatan);
            stat.setString(7, p.gaji);
            stat.setString(8, p.tanggal_masuk);
            stat.setString(9,inputId.getText());
            stat.executeUpdate();
            refreshTable();
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DI UBAH !");
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgPegawai;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboJKL;
    private com.toedter.calendar.JDateChooser inpuTglMasuk;
    private javax.swing.JTextField inputAlamat;
    private javax.swing.JTextField inputGaji;
    private javax.swing.JTextField inputId;
    private javax.swing.JTextField inputJabatan;
    private javax.swing.JTextField inputNama;
    private javax.swing.JTextField inputTelp;
    private com.toedter.calendar.JDateChooser inputTglLahir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTable tblPegawai;
    // End of variables declaration//GEN-END:variables

    private void Icons() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("apk-logo .png")));
    }
}
